server.port=8082
spring.application.name=user-service
  
  # Database
spring.datasource.url=jdbc:postgresql://localhost:5432/pgoptima-user
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
  
  # JWT validation (shared secret with auth-service)
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.issuer=pgoptima-auth-service
  
  # Encryption
encryption.secret-key=${ENCRYPTION_SECRET:MySuperSecretKeyForAES256Length32Bytes!!}
encryption.salt=PgOptimaSalt
  
  # Logging
logging.level.com.pgoptima.userservice=DEBUG
  
  # Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.prometheus.metrics.export.enabled=true